#!/usr/bin/env python3

from __future__ import annotations

import gc
import os
import sys
import time
from pathlib import Path

import numpy as np

ESSOS_ROOT  = Path(__file__).resolve().parents[2]
SIMSOPT_SRC = ESSOS_ROOT.parent / "simsopt" / "src"

# MUSE
SURF_FILE     = ESSOS_ROOT / "essos" / "input.muse"
COIL_FILE     = SIMSOPT_SRC.parent / "tests" / "test_files" / "muse_tf_coils.focus"
MAG_FILE      = SIMSOPT_SRC.parent / "tests" / "test_files" / "zot80.focus"
SURFACE_RANGE = "half period"

# Rotating ellipse
# SURF_FILE     = ESSOS_ROOT / "essos" / "examples" / "input_rot_ellipse_nfp8_e_1p98"
# COIL_FILE     = ESSOS_ROOT / "essos" / "examples" / "rot_ellipse_nfp8_e_198.focus"
# MAG_FILE      = ESSOS_ROOT / "essos" / "examples" / "dipole_grid_nfp8.focus"
# SURFACE_RANGE = "half period"

SURFACE_NPHI   = 64
SURFACE_NTHETA = 64

OUTPUT_DIR = Path("pm_opt_output")


JAX_PLATFORM = "cpu"
CPU_THREADS  = 4
ENABLE_X64   = True

FB_ONLY_STEPS       = 8000
FB_ONLY_LR_MAX      = 0.01
FB_ONLY_LR_MIN_FRAC = 0.1

FD_ANNEAL_STEPS       = 6000
FD_ANNEAL_LR_MAX      = 0.001
FD_ANNEAL_LR_MIN_FRAC = 0.001

MAX_WD        = 0.2
WD_RAMP_POWER = 4      #  wD = (progress)^WD_RAMP_POWER * MAX_WD
LOG_INTERVAL  = 500

VOLUME_TARGET_CM3 = 0.0   # 0 disables
W_VOLUME_TARGET   = 1.0

B_MAX_T = 1.465
MU0     = 4 * np.pi * 1e-7

if "jax" in sys.modules:
    print("WARNING: JAX already imported — device selection may not take effect.")

if JAX_PLATFORM != "auto":
    os.environ["JAX_PLATFORMS"] = JAX_PLATFORM

if JAX_PLATFORM == "cpu":
    xla_flag = f"--xla_cpu_multi_thread_eigen=true intra_op_parallelism_threads={CPU_THREADS}"
    existing = os.environ.get("XLA_FLAGS", "").strip()
    if xla_flag not in existing:
        os.environ["XLA_FLAGS"] = f"{existing} {xla_flag}".strip()
    for var in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS"):
        os.environ.setdefault(var, str(CPU_THREADS))

import jax
import jax.numpy as jnp

jax.config.update("jax_enable_x64", ENABLE_X64)
backend_name = str(jax.default_backend()).lower()
print(f"JAX backend: {backend_name}  |  devices: {[str(d) for d in jax.devices()]}")

for p in [str(ESSOS_ROOT), str(SIMSOPT_SRC)]:
    if p not in sys.path:
        sys.path.insert(0, p)

from essos.fields import DipoleField

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def load_surface(surf_file, surface_range, nphi, ntheta):
    from simsopt.geo import SurfaceRZFourier
    try:
        surface = SurfaceRZFourier.from_vmec_input(str(surf_file), range=surface_range, nphi=nphi, ntheta=ntheta)
    except Exception:
        surface = SurfaceRZFourier.from_focus(str(surf_file), range=surface_range, nphi=nphi, ntheta=ntheta)
    return surface


def load_coils_essos(coil_file):

    from simsopt.field import Coil, Current
    from simsopt.util.permanent_magnet_helper_functions import read_focus_coils
    from essos.coils import Coils_from_simsopt

    base_curves, base_currents0, ncoils = read_focus_coils(str(coil_file))
    total_current = float(np.sum([c.get_value() for c in base_currents0]))
    all_coils = [Coil(base_curves[i], Current(total_current / ncoils)) for i in range(ncoils)]

    coils = Coils_from_simsopt(all_coils, nfp=1, stellsym=False)
    return coils


def compute_Bn_fixed_essos(coils, surf_pts, surf_n):
    from essos.fields import BiotSavart
    field = BiotSavart(coils)
    surf_pts_jax = jnp.asarray(surf_pts, jnp.float64)
    B_at_pts = jax.vmap(field.B)(surf_pts_jax)
    Bn = jnp.sum(B_at_pts * jnp.asarray(surf_n, jnp.float64), axis=1)
    return np.asarray(Bn, np.float64)


def load_magnet_grid(mag_file):
    """Read FOCUS-format magnet grid: positions, moments, and pho (column 8)."""
    pos_list, mom_list, pho_list = [], [], []
    with open(str(mag_file), encoding="utf-8") as f:
        for line in f.readlines()[3:]:
            tokens = line.replace(",", " ").split()
            if len(tokens) < 12:
                continue
            x, y, z = float(tokens[3]), float(tokens[4]), float(tokens[5])
            m0      = float(tokens[7])
            pho     = float(tokens[8])
            az, pol = float(tokens[10]), float(tokens[11])
            pos_list.append((x, y, z))
            mom_list.append((m0*np.cos(az)*np.sin(pol), m0*np.sin(az)*np.sin(pol), m0*np.cos(pol)))
            pho_list.append(pho)
    return (
        np.asarray(pos_list, np.float64),
        np.asarray(mom_list, np.float64),
        np.asarray(pho_list, np.float64),
    )


def write_focus_file(path, positions, moments, pho, header="generated by muse_pm_optimize"):
    """Write a FOCUS-format magnet grid file: positions, moments, pho."""
    n = len(positions)
    m0 = np.linalg.norm(moments, axis=1)
    m0_safe = np.where(m0 > 0, m0, 1.0)
    mhat = moments / m0_safe[:, None]
    pol = np.arccos(np.clip(mhat[:, 2], -1, 1))
    az  = np.arctan2(mhat[:, 1], mhat[:, 0])
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# {header}\n")
        f.write("# Total number of dipoles\n")
        f.write(f"{n}\n")
        f.write("#coiltype, symmetry,  ox,  oy,  oz,  Ic,  M0,  pho,  Lc,  mp,  mt\n")
        for i in range(n):
            f.write(
                f"2, 2, {positions[i,0]:.8e}, {positions[i,1]:.8e}, {positions[i,2]:.8e}, "
                f"0, {m0[i]:.8e}, {pho[i]:.8e}, 0, {az[i]:.8e}, {pol[i]:.8e}\n"
            )
    print(f"Wrote {n} magnets to {path}")


print(f"\n--- Loading surface: {SURF_FILE.name} ---")
surface = load_surface(SURF_FILE, SURFACE_RANGE, SURFACE_NPHI, SURFACE_NTHETA)
nfp      = int(surface.nfp)
stellsym = bool(surface.stellsym)
print(f"Surface nfp={nfp}  stellsym={stellsym}  (read from surface file)")

surf_xyz = np.asarray(surface.gamma(), np.float64)
surf_nrm = np.asarray(surface.unitnormal(), np.float64)
surf_pts = surf_xyz.reshape(-1, 3)
surf_n   = surf_nrm.reshape(-1, 3)
area_weight = float(surface.area() / len(surf_pts))

print(f"\n--- Loading coils (essos-native): {COIL_FILE.name} ---")
essos_coils = load_coils_essos(COIL_FILE)
Bn_fixed = compute_Bn_fixed_essos(essos_coils, surf_pts, surf_n)

print(f"\n--- Loading magnet grid: {MAG_FILE.name} ---")
magnet_positions, magnet_moments_raw, pho_loaded = load_magnet_grid(MAG_FILE)
n_magnets = len(magnet_positions)

native_norms = np.linalg.norm(magnet_moments_raw, axis=1)
M0_SCALE = float(np.mean(native_norms))
magnet_orientations = magnet_moments_raw / native_norms[:, None]
magnet_moments = magnet_orientations * M0_SCALE

M_MAX = B_MAX_T / MU0
volume_per_cell = (M0_SCALE / M_MAX) * 1e6

print(f"Magnets loaded: {n_magnets}  |  M0={M0_SCALE:.6f} A\u00b7m\u00b2  |  V_cell={volume_per_cell:.4f} cm\u00b3")
print(f"Loaded pho: {int(np.sum(np.abs(pho_loaded) > 0.5))} active magnets "
      f"({100*np.sum(np.abs(pho_loaded) > 0.5)/n_magnets:.1f}%)")

print("=" * 70)
print("PM Optimization — fB + Discreteness (start at loaded solution)")
print(f"Backend: {backend_name}")
print("=" * 70)


# BUILD G MATRIX 

print("\n--- Build G matrix ---")
JAX_DTYPE        = jnp.float32
surface_pts_flat = jnp.asarray(surf_pts, JAX_DTYPE)
surface_nrm_flat = jnp.asarray(surf_n,   JAX_DTYPE)

t0 = time.time()
dipole_field = DipoleField(
    jnp.asarray(magnet_positions, JAX_DTYPE),
    jnp.asarray(magnet_moments,   JAX_DTYPE),
    jnp.zeros(n_magnets, JAX_DTYPE),
    nfp=nfp, stellsym=stellsym, scale_factor=1.0,
)
G = np.asarray(dipole_field.compute_interaction_matrix(surface_pts_flat, surface_nrm_flat), np.float32)
gc.collect()
print(f"G: {G.shape}  {G.nbytes/1e9:.2f} GB  {time.time()-t0:.1f}s")

G_jax  = jnp.asarray(G)
Bn_jax = jnp.asarray(Bn_fixed, jnp.float32)
aw_jax = jnp.float32(area_weight)
vc_jax = jnp.float32(volume_per_cell)
f32    = jnp.float32

fB_gen0 = float(0.5 * np.dot(pho_loaded @ G.T.astype(np.float64) + Bn_fixed,
                             pho_loaded @ G.T.astype(np.float64) + Bn_fixed) * area_weight)
print(f"fB (loaded solution) = {fB_gen0:.4e}")

fB_ref  = jnp.float32(max(fB_gen0, 1e-20))
Vt_jax  = jnp.float32(VOLUME_TARGET_CM3)
wVT_jax = jnp.float32(W_VOLUME_TARGET)


@jax.jit
def compute_metrics(pho):
    bn    = pho @ G_jax.T + Bn_jax
    fB    = f32(0.5) * jnp.sum(bn * bn) * aw_jax
    abs_p = jnp.sqrt(pho * pho + f32(1e-7))
    fV    = vc_jax * jnp.sum(abs_p)
    fD    = jnp.sum(abs_p * (f32(1) - abs_p))
    return fB, fV, fD


@jax.jit
def adam_step(pho, m, v, lr, w_fD):
    """
    One Adam step: L = fB/fB_ref + w_fD * fD + wVT * max(fV-Vt, 0).
    """
    def loss(x):
        bn    = x @ G_jax.T + Bn_jax
        fB    = f32(0.5) * jnp.sum(bn * bn) * aw_jax
        abs_p = jnp.sqrt(x * x + f32(1e-7))
        fV    = vc_jax * jnp.sum(abs_p)
        fD    = jnp.sum(abs_p * (f32(1) - abs_p))
        fVT_raw = jnp.maximum(fV - Vt_jax, f32(0))
        fVT     = jnp.where(Vt_jax > f32(0), fVT_raw, f32(0))
        return fB / fB_ref + w_fD * fD + fVT * wVT_jax
    b1, b2, eps = f32(0.9), f32(0.999), f32(1e-8)
    g    = jax.grad(loss)(pho)
    m    = b1*m + (1-b1)*g
    v    = b2*v + (1-b2)*g*g
    pho  = jnp.clip(pho - lr * m / (jnp.sqrt(v) + eps), -1, 1)
    return pho, m, v


def cosine_lr(step, total, lr_max, lr_min):
    return lr_min + 0.5*(lr_max - lr_min)*(1 + np.cos(np.pi*step/max(total, 1)))


def get_lr_and_wd(step):
    if step <= FB_ONLY_STEPS:
        lr_min = FB_ONLY_LR_MAX * FB_ONLY_LR_MIN_FRAC
        return cosine_lr(step-1, FB_ONLY_STEPS, FB_ONLY_LR_MAX, lr_min), 0.0
    s      = step - FB_ONLY_STEPS
    lr_min = FD_ANNEAL_LR_MAX * FD_ANNEAL_LR_MIN_FRAC
    lr     = cosine_lr(s-1, FD_ANNEAL_STEPS, FD_ANNEAL_LR_MAX, lr_min)
    wD     = ((s-1) / max(FD_ANNEAL_STEPS-1, 1)) ** WD_RAMP_POWER * MAX_WD
    return lr, wD


TOTAL_STEPS = FB_ONLY_STEPS + FD_ANNEAL_STEPS

print(f"\n{'='*70}")
print(f"Stage 1 (fB only):   {FB_ONLY_STEPS} steps  LR {FB_ONLY_LR_MAX} \u2192 {FB_ONLY_LR_MAX*FB_ONLY_LR_MIN_FRAC:.4f}")
print(f"Stage 2 (fD anneal): {FD_ANNEAL_STEPS} steps  LR {FD_ANNEAL_LR_MAX} \u2192 {FD_ANNEAL_LR_MAX*FD_ANNEAL_LR_MIN_FRAC:.5f}  wD 0\u2192{MAX_WD} (power={WD_RAMP_POWER})")
print(f"Volume target: {'disabled' if VOLUME_TARGET_CM3 <= 0 else f'{VOLUME_TARGET_CM3:.0f} cm3, wVT={W_VOLUME_TARGET} (one-sided)'}")
print(f"{'='*70}")

G64  = G.astype(np.float64)
Bn64 = Bn_fixed.astype(np.float64)
fB_coils = float(0.5 * np.dot(Bn64, Bn64) * area_weight)
print(f"[ref] fB coils-only:   {fB_coils:.4e}")
print(f"[ref] fB loaded:       {fB_gen0:.4e}   fV: {volume_per_cell*np.abs(pho_loaded).sum():.1f} cm\u00b3")


def fB64_of(p):
    r = p @ G64.T + Bn64
    return 0.5 * np.sum(r*r) * area_weight


t_start = time.time()

# No parallel-starts batch dimension — single trajectory starting AT the
# loaded solution (e.g. zot80's existing optimized pho), not zero/random.
pho = jnp.asarray(np.clip(pho_loaded, -1, 1), jnp.float32)
mom = jnp.zeros_like(pho)
var = jnp.zeros_like(pho)

lr0, wd0 = get_lr_and_wd(1)
pho, mom, var = adam_step(pho, mom, var, f32(lr0), f32(wd0))
_ = pho.block_until_ready()
print("JIT compiled.")

fB_s1 = None
for step in range(2, TOTAL_STEPS + 1):
    lr, wD = get_lr_and_wd(step)
    pho, mom, var = adam_step(pho, mom, var, f32(lr), f32(wD))

    if step <= FB_ONLY_STEPS and (step % LOG_INTERVAL == 0 or step == FB_ONLY_STEPS):
        fB_t, fV_t, _ = compute_metrics(pho)
        clip = float(jnp.mean(jnp.abs(pho) > 0.99)) * 100
        print(f"[Stage 1] {step:5d}/{FB_ONLY_STEPS}  fB={float(fB_t):.4e}  "
              f"fV={float(fV_t):.1f}  clip={clip:.1f}%  lr={lr:.4f}")

    if step == FB_ONLY_STEPS:
        p1    = np.asarray(pho, np.float64)
        fB_s1 = fB64_of(p1)
        ap1   = np.abs(p1)
        lo, mid_lo, mid_hi = np.mean(ap1 < 0.05), np.mean((ap1 >= 0.05) & (ap1 < 0.5)), np.mean((ap1 >= 0.5) & (ap1 < 0.95))
        p_r   = np.sign(p1) * (ap1 > 0.5)
        print(f"[S1 done] fB={fB_s1:.4e}  ({fB_s1/fB_coils:.1e}x coils, {fB_s1/fB_gen0:.2f}x loaded)")
        print(f"[S1 dist] |p|<.05: {lo*100:.0f}%   .05-.5: {mid_lo*100:.0f}%   .5-.95: {mid_hi*100:.0f}%")
        print(f"[control] naive-round fB={fB64_of(p_r):.4e}  fV={volume_per_cell*np.abs(p_r).sum():.1f}")

    if step > FB_ONLY_STEPS and (step % LOG_INTERVAL == 0 or step == TOTAL_STEPS):
        fB_t, fV_t, fD_t = compute_metrics(pho)
        disc = float(jnp.mean((jnp.abs(pho) < 0.05) | (jnp.abs(pho) > 0.95))) * 100
        s    = step - FB_ONLY_STEPS
        print(f"[Anneal] {s:5d}/{FD_ANNEAL_STEPS}  fB={float(fB_t):.4e} ({float(fB_t)/fB_s1:.1f}x S1)  "
              f"fV={float(fV_t):.1f}  fD={float(fD_t):.1f}  wD={wD:.4f}  disc={disc:.0f}%")

p   = np.asarray(pho, np.float64)
p_d = np.sign(p) * (np.abs(p) > 0.5)
fB_fin, fB_rnd = fB64_of(p), fB64_of(p_d)

print(f"\n{'='*70}")
print(f"Done in {time.time()-t_start:.0f}s")
print(f"  Stage 1 (continuous bound): {fB_s1:.4e}")
print(f"  annealed (still smooth):    {fB_fin:.4e}  ({fB_fin/fB_s1:.1f}x S1)")
print(f"  hard-rounded (buildable):   {fB_rnd:.4e}  ({fB_rnd/fB_s1:.1f}x S1)  fV={volume_per_cell*np.abs(p_d).sum():.1f}")
print(f"  vs loaded: {fB_rnd/fB_gen0:.2f}x   vs coils-only: {fB_rnd/fB_coils:.1e}x")

n_active = int(np.sum(np.abs(p_d) > 0.5))
print(f"  Active magnets: {n_active} / {n_magnets} ({100*n_active/n_magnets:.1f}%)")
print(f"    North (+1): {int(np.sum(p_d > 0.5))}   South (-1): {int(np.sum(p_d < -0.5))}   Off: {n_magnets - n_active}")
print(f"{'='*70}")

# SAVE OUTPUTS — .npy 
np.save(OUTPUT_DIR / "pho_optimized.npy",  p_d)
np.save(OUTPUT_DIR / "pho_continuous.npy", p)
np.save(OUTPUT_DIR / "grid_positions.npy", magnet_positions)
np.save(OUTPUT_DIR / "grid_moments.npy",   magnet_moments)


# pho is +1, flipped where pho is -1, zero where pho is 0.
final_moments = np.where(p_d[:, None] != 0, magnet_orientations * M0_SCALE, 0.0) * np.sign(p_d)[:, None]
write_focus_file(OUTPUT_DIR / "pm_optimized.focus", magnet_positions, final_moments, p_d)

print(f"\nSaved outputs to {OUTPUT_DIR}/")

del G_jax, Bn_jax
gc.collect()
jax.clear_caches()


# PLOTTING

import matplotlib.pyplot as plt

nphi_s, ntheta_s = surf_xyz.shape[0], surf_xyz.shape[1]
phi_coords   = np.linspace(0, 1, nphi_s)
theta_coords = np.linspace(0, 1, ntheta_s)

Bn_before = Bn_fixed.reshape(nphi_s, ntheta_s)
Bn_pm     = (G64 @ p_d).reshape(nphi_s, ntheta_s)
Bn_after  = Bn_before + Bn_pm

abs_max = max(np.abs(Bn_before).max(), np.abs(Bn_after).max())
levels  = np.linspace(-abs_max, abs_max, 21)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
im1 = axes[0].contourf(phi_coords, theta_coords, Bn_before.T, levels=levels, cmap="RdBu_r", extend="both")
axes[0].set_title("Coils only (before)", fontsize=12)
axes[0].set_xlabel("phi"); axes[0].set_ylabel("theta")
plt.colorbar(im1, ax=axes[0], label="B\u00b7n [T]")
rms_before = float(np.sqrt(np.mean(Bn_before**2)))
axes[0].text(0.02, 0.97, f"RMS = {rms_before:.3e} T", transform=axes[0].transAxes,
             va="top", fontsize=10, bbox=dict(boxstyle="round", facecolor="white", alpha=0.8))

im2 = axes[1].contourf(phi_coords, theta_coords, Bn_after.T, levels=levels, cmap="RdBu_r", extend="both")
axes[1].set_title("Coils + optimized PMs (after)", fontsize=12)
axes[1].set_xlabel("phi")
plt.colorbar(im2, ax=axes[1], label="B\u00b7n [T]")
rms_after = float(np.sqrt(np.mean(Bn_after**2)))
axes[1].text(0.02, 0.97, f"RMS = {rms_after:.3e} T", transform=axes[1].transAxes,
             va="top", fontsize=10, bbox=dict(boxstyle="round", facecolor="white", alpha=0.8))

plt.suptitle(f"fB={fB_rnd:.2e}  fV={volume_per_cell*np.abs(p_d).sum():.0f} cm\u00b3  "
             f"RMS: {rms_before:.3e} \u2192 {rms_after:.3e} T  ({rms_before/rms_after:.1f}\u00d7)", fontsize=12)
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "Bn_before_after.png", dpi=200, bbox_inches="tight")
plt.show()
print(f"Saved {OUTPUT_DIR}/Bn_before_after.png")
